import { useRouter } from "next/router";

import React, { use, useState } from "react";
import Head from "next/head";
import Header from "../../components/ui/Header";
import Intro from "../../components/ui/Intro/Intro";
import ProductsContainer from "../../components/ui/ProductsContainer/ProductsContainer";
import useData from "../../Hooks/useData";
import { useDispatch, useSelector } from "react-redux";
import { addCartItem } from "../../slices/cartSlice";
import componentData from "../../data/ProductPage.json";
export default function HomePage() {
  const [data, isLoading] = useData(
    "https://orders.fore-site.net/media_admin/api/api_secure.php?module=inventory&method=category_products&sk1=DICOSECSK1oolshdsf33sadGGHsd376&debug=yes&device_id=33333333&data=1&filter1=55&lang=en&username=28&field_subcategory=151",
    "data"
  );
  const [title, setTitle] = useState("");
  const [width, setWidth] = useState(0);
  const [height, setHeight] = useState(0);
  const router = useRouter();
  const label = router.query;
  const dispatch = useDispatch();
  const cart = useSelector((state) => state.cart);
  const item = cart.find((x) => x.item.label == label.label);
  const language = useSelector((state) => state.language);
  const uiData =
    language == "arabic" ? componentData.arabic : componentData.english;

  const [counter, setCounter] = useState(item ? item.quantity : 1);
  return (
    <div>
      <Head>
        <title>Intex Store {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <Header />
      <div className="mt-28 p-5">
        {isLoading ? (
          <img className=" h-screen w-screen" src="/Assets/GIF/Loading.gif" />
        ) : (
          <div className=" flex items-center">
            {data.data.res
              .filter((x) => x.label == label.label)
              .map((product, index) => (
                <div key={index} className="h-fit w-full">
                  <div className=" flex w-full flex-wrap items-center justify-evenly border-b">
                    <img
                      className="aspect-square h-fit w-full max-w-lg object-contain tablet:w-1/2 tablet:min-w-[400px]"
                      src={product.image}
                    />

                    <article className="ml-4 h-fit w-full font-bold tablet:w-1/2">
                      <div>
                        <h1 className=" text-blue-gray my-2 text-3xl">
                          {product.field_item_name}
                        </h1>
                        <h2 className="  w-full border-b pb-10 font-normal capitalize">
                          {uiData.itemNumber}: {product.label}
                        </h2>
                      </div>
                      <div className=" flex flex-col">
                        <p className=" my-5 ml-auto text-2xl capitalize">
                          {product.field_wholesale_price * 1.5} JOD
                        </p>

                        <div className=" ml-auto flex w-full text-center shadow-md tablet:w-fit">
                          <button
                            onClick={() => {
                              if (counter > 0) {
                                setCounter(counter - 1);
                              }
                            }}
                            className=" rounded-l-xl bg-slate-800 p-2 px-3 font-bold text-white"
                          >
                            -
                          </button>
                          <p className=" flex-1 py-2 tablet:px-24">{counter}</p>

                          <button
                            onClick={() => setCounter(counter + 1)}
                            className=" rounded-r-xl bg-slate-800 py-2 px-3 font-bold text-white"
                          >
                            +
                          </button>
                        </div>
                        <button
                          onClick={() => {
                            if (counter != 0) {
                              dispatch(
                                addCartItem({
                                  item: {
                                    image: product.image,
                                    discription: product.field_item_name,
                                    label: product.label,
                                    price: product.field_wholesale_price * 1.5,
                                  },
                                  quantity: counter,
                                })
                              );
                            } else {
                              alert("Set A Quantity Please!");
                            }
                          }}
                          className=" bg-secondery hover:text-secondery hover:border-secondery my-5 ml-auto w-full rounded-xl border-2 border-transparent px-20 py-2 font-bold uppercase text-white hover:bg-white tablet:w-fit"
                        >
                          {uiData.addToCartButton}
                        </button>
                      </div>
                    </article>
                  </div>
                  <ProductsContainer
                    title={uiData.relatedProducts}
                    limit={3}
                    number={product.field_subcategory}
                  />
                </div>
              ))}
          </div>
        )}
      </div>
    </div>
  );
}
