import { useRouter } from "next/router";

import React, { use, useState } from "react";
import Head from "next/head";
import Header from "../../components/ui/Header";
import Intro from "../../components/ui/Intro/Intro";
import ProductsContainer from "../../components/ui/ProductsContainer/ProductsContainer";
import useData from "../../Hooks/useData";
import { useDispatch, useSelector } from "react-redux";
import { addCartItem } from "../../slices/cartSlice";
import componentData from "../../data/ProductPage.json";
export default function HomePage() {
  const [data, isLoading] = useData(
    "https://orders.fore-site.net/media_admin/api/api_secure.php?module=inventory&method=category_products&sk1=DICOSECSK1oolshdsf33sadGGHsd376&debug=yes&device_id=33333333&data=1&filter1=55&lang=en&username=28&field_subcategory=151",
    "data"
  );
  const [title, setTitle] = useState("");
  const [width, setWidth] = useState(0);
  const [height, setHeight] = useState(0);
  const router = useRouter();
  const label = router.query;
  const dispatch = useDispatch();
  const cart = useSelector((state) => state.cart);
  const item = cart.find((x) => x.item.label == label.label);
  const language = useSelector((state) => state.language);
  const uiData =
    language == "arabic" ? componentData.arabic : componentData.english;

  const [counter, setCounter] = useState(item ? item.quantity : 1);
  return (
    <div>
      <Head>
        <title>Intex Store {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <Header />
      <div className="p-5 mt-28">
        {isLoading ? (
          <img className=" h-screen w-screen" src="/Assets/GIF/Loading.gif" />
        ) : (
          <div className=" flex items-center">
            {data.data.res
              .filter((x) => x.label == label.label)
              .map((product, index) => (
                <div key={index} className="w-full min-h-screen">
                  <div className=" border-b flex w-full min-h-screen items-center flex-wrap justify-evenly">
                    <img
                      className="tablet:w-1/2 w-full tablet:min-w-[400px] max-w-lg h-fit aspect-square object-contain"
                      src={product.image}
                    />

                    <article className="tablet:w-1/2 w-full font-bold h-fit">
                      <div>
                        <h1 className=" text-3xl my-2 text-blue-gray">
                          {product.field_item_name}
                        </h1>
                        <h2 className="  capitalize w-full font-normal border-b pb-10">
                          {uiData.itemNumber}: {product.label}
                        </h2>
                      </div>
                      <div className=" flex flex-col">
                        <p className=" text-2xl capitalize my-5 ml-auto">
                          {product.field_wholesale_price * 1.5} JOD
                        </p>

                        <div className=" flex ml-auto tablet:w-fit w-full text-center shadow-md">
                          <button
                            onClick={() => {
                              if (counter > 0) {
                                setCounter(counter - 1);
                              }
                            }}
                            className=" bg-slate-800 text-white font-bold rounded-l-xl p-2 px-3"
                          >
                            -
                          </button>
                          <p className=" tablet:px-24 flex-1 py-2">{counter}</p>

                          <button
                            onClick={() => setCounter(counter + 1)}
                            className=" bg-slate-800 text-white font-bold rounded-r-xl py-2 px-3"
                          >
                            +
                          </button>
                        </div>
                        <button
                          onClick={() => {
                            if (counter != 0) {
                              dispatch(
                                addCartItem({
                                  item: {
                                    image: product.image,
                                    discription: product.field_item_name,
                                    label: product.label,
                                    price: product.field_wholesale_price * 1.5,
                                  },
                                  quantity: counter,
                                })
                              );
                            } else {
                              alert("Set A Quantity Please!");
                            }
                          }}
                          className=" border-transparent bg-secondery uppercase tablet:w-fit w-full text-white ml-auto px-20 rounded-xl py-2 font-bold my-5 hover:bg-white hover:text-secondery hover:border-secondery border-2"
                        >
                          {uiData.addToCartButton}
                        </button>
                      </div>
                    </article>
                  </div>
                  <ProductsContainer
                    title={uiData.relatedProducts}
                    limit={3}
                    number={product.field_subcategory}
                  />
                </div>
              ))}
          </div>
        )}
      </div>
    </div>
  );
}
