import { useRouter } from "next/router";

import React, { use, useState } from "react";
import Head from "next/head";
import Header from "../../components/ui/Header";
import Intro from "../../components/ui/Intro/Intro";
import ProductsContainer from "../../components/ui/ProductsContainer/ProductsContainer";
import Chevron from "../../public/Assets/icons/chevron";
import useData from "../../Hooks/useData";
// import ReactImageMagnify from "react-image-magnify";

export default function HomePage() {
  const [data, isLoading] = useData(
    "https://orders.fore-site.net/media_admin/api/api_secure.php?module=inventory&method=category_products&sk1=DICOSECSK1oolshdsf33sadGGHsd376&debug=yes&device_id=33333333&data=1&filter1=55&lang=en&username=28&field_subcategory=151",
    "data"
  );
  const [counter, setCounter] = useState(0);
  const [width, setWidth] = useState(0);
  const [height, setHeight] = useState(0);
  const router = useRouter();
  const label = router.query;

  return (
    <div>
      <Head>
        <title>Intex Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <Header />
      <div className="p-5">
        {isLoading ? (
          <img className=" h-screen w-screen" src="/Assets/GIF/Loading.gif" />
        ) : (
          <div className=" flex items-center">
            {/* {data.data.res
              .filter((x) => x.label == label.label)
              .map((product, index) => {
                const dimensions = new Image();
                dimensions.src = product.image;

                dimensions.onload = function () {
                  setHeight(this.height);
                  setWidth(this.width);
                };
              })} */}
            {data.data.res
              .filter((x) => x.label == label.label)
              .map((product, index) => (
                <div key={index} className="w-full min-h-screen">
                  <div className=" border-b flex w-full h-screen items-center justify-evenly">
                    <img className="w-1/2 max-w-lg h-fit" src={product.image} />
                    {}

                    {/* <div
                      style={{ flex: "0 0 30%", margin: "20px 0 20px 20px" }}
                    >
                      <ReactImageMagnify
                        {...{
                          smallImage: {
                            alt: "Wristwatch by Ted Baker London",
                            isFluidWidth: true,
                            src: product.image,
                            // src: "https://cdn11.bigcommerce.com/s-u7yn5f7nmq/images/stencil/640w/products/3954/7879/68303EP_Main__44538.1632861542.jpg?c=2",
                          },
                          largeImage: {
                            src: product.image,
                            // src: "https://cdn11.bigcommerce.com/s-u7yn5f7nmq/images/stencil/640w/products/3954/7879/68303EP_Main__44538.1632861542.jpg?c=2",
                            width: width * 5.555555555555556,
                            height: height * 5.555555555555556,
                          },
                          enlargedImageContainerDimensions: {
                            width: "200%",
                            height: "100%",
                          },
                        }}
                      />
                    </div> */}
                    <article className="w-1/2 font-bold h-fit">
                      <div>
                        <h1 className=" text-3xl my-2 text-blue-gray">
                          {product.field_item_name}
                        </h1>
                        <h2 className="  capitalize w-full font-normal border-b pb-10">
                          item number: {product.label}
                        </h2>
                      </div>
                      <div className=" flex flex-col">
                        <p className=" text-2xl capitalize my-5 ml-auto">
                          {product.field_wholesale_price * 1.5} JOD
                        </p>

                        <div className=" flex ml-auto shadow-md">
                          <button
                            onClick={() => setCounter(counter + 1)}
                            className=" bg-slate-800 text-white font-bold rounded-l-xl py-2 px-3"
                          >
                            +
                          </button>
                          <p className=" px-24 py-2">{counter}</p>
                          <button
                            onClick={() => {
                              if (counter > 0) {
                                setCounter(counter - 1);
                              }
                            }}
                            className=" bg-slate-800 text-white font-bold rounded-r-xl p-2 px-3"
                          >
                            -
                          </button>
                        </div>
                        <button className=" border-transparent bg-secondery uppercase text-white ml-auto px-20 rounded-xl py-2 font-bold my-5 hover:bg-white hover:text-secondery hover:border-secondery border-2">
                          Add to Cart
                        </button>
                      </div>
                    </article>
                  </div>
                  <ProductsContainer
                    title={"Related Products"}
                    limit={3}
                    number={product.field_subcategory}
                  />
                </div>
              ))}
          </div>
        )}
      </div>
    </div>
  );
}
