import { useRouter } from "next/router";

import React from "react";
import Head from "next/head";
import Header from "../../components/ui/Header";
import Intro from "../../components/ui/Intro/Intro";
import ProductsContainer from "../../components/ui/ProductsContainer/ProductsContainer";

export default function HomePage() {
  const router = useRouter();
  const products = router.query;
  console.log(products);
  return (
    <div>
      <Head>
        <title>Intex Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <Header />
      <div className=" mt-28">
        <img className="w-full" src="/Assets/images/intro/hero2.jpg" alt="" />
        <ProductsContainer
          number={products.products}
          limit={0}
          title={products.title}
        />
      </div>
    </div>
  );
}
