import React from "react";
import Head from "next/head";
import Header from "../../components/ui/Header";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Intex Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <Header />
    </div>
  );
}
